In [30]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as lda
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import GridSearchCV, RepeatedStratifiedKFold

In [2]:
data = pd.read_csv('Live.csv')
data

status_id status_type status_published  \
0      246675545449582_1649696485147474       video   4/22/2018 6:00   
1      246675545449582_1649426988507757       photo  4/21/2018 22:45   
2      246675545449582_1648730588577397       video   4/21/2018 6:17   
3      246675545449582_1648576705259452       photo   4/21/2018 2:29   
4      246675545449582_1645700502213739       photo   4/18/2018 3:22   
...                                 ...         ...              ...   
7045  1050855161656896_1061863470556065       photo   9/24/2016 2:58   
7046  1050855161656896_1061334757275603       photo  9/23/2016 11:19   
7047  1050855161656896_1060126464063099       photo  9/21/2016 23:03   
7048  1050855161656896_1058663487542730       photo   9/20/2016 0:43   
7049  1050855161656896_1050858841656528       photo  9/10/2016 10:30   

      num_reactions  num_comments  num_shares  num_likes  num_loves  num_wows  \
0               529           512         262        432         92         3   
1               150             0           0        150          0         0   
2               227           236          57        204         21         1   
3               111             0           0        111          0         0   
4               213             0           0        204          9         0   
...             ...           ...         ...        ...        ...       ...   
7045             89             0           0         89          0         0   
7046             16             0           0         14          1         0   
7047              2             0           0          1          1         0   
7048            351            12          22        349          2         0   
7049             17             0           0         17          0         0   

      num_hahas  num_sads  num_angrys  Column1  Column2  Column3  Column4  
0             1         1           0      NaN      NaN      NaN      NaN  
1             0         0           0      NaN      NaN      NaN      NaN  
2             1         0           0      NaN      NaN      NaN      NaN  
3             0         0           0      NaN      NaN      NaN      NaN  
4             0         0           0      NaN      NaN      NaN      NaN  
...         ...       ...         ...      ...      ...      ...      ...  
7045          0         0           0      NaN      NaN      NaN      NaN  
7046          1         0           0      NaN      NaN      NaN      NaN  
7047          0         0           0      NaN      NaN      NaN      NaN  
7048          0         0           0      NaN      NaN      NaN      NaN  
7049          0         0           0      NaN      NaN      NaN      NaN  

[7050 rows x 16 columns]

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7050 entries, 0 to 7049
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   status_id         7050 non-null   object 
 1   status_type       7050 non-null   object 
 2   status_published  7050 non-null   object 
 3   num_reactions     7050 non-null   int64  
 4   num_comments      7050 non-null   int64  
 5   num_shares        7050 non-null   int64  
 6   num_likes         7050 non-null   int64  
 7   num_loves         7050 non-null   int64  
 8   num_wows          7050 non-null   int64  
 9   num_hahas         7050 non-null   int64  
 10  num_sads          7050 non-null   int64  
 11  num_angrys        7050 non-null   int64  
 12  Column1           0 non-null      float64
 13  Column2           0 non-null      float64
 14  Column3           0 non-null      float64
 15  Column4           0 non-null      float64
dtypes: float64(4), int64(9), object(3)
memory 

In [4]:
data.describe().T

count        mean         std  min   25%   50%     75%  \
num_reactions  7050.0  230.117163  462.625309  0.0  17.0  59.5  219.00   
num_comments   7050.0  224.356028  889.636820  0.0   0.0   4.0   23.00   
num_shares     7050.0   40.022553  131.599965  0.0   0.0   0.0    4.00   
num_likes      7050.0  215.043121  449.472357  0.0  17.0  58.0  184.75   
num_loves      7050.0   12.728652   39.972930  0.0   0.0   0.0    3.00   
num_wows       7050.0    1.289362    8.719650  0.0   0.0   0.0    0.00   
num_hahas      7050.0    0.696454    3.957183  0.0   0.0   0.0    0.00   
num_sads       7050.0    0.243688    1.597156  0.0   0.0   0.0    0.00   
num_angrys     7050.0    0.113191    0.726812  0.0   0.0   0.0    0.00   
Column1           0.0         NaN         NaN  NaN   NaN   NaN     NaN   
Column2           0.0         NaN         NaN  NaN   NaN   NaN     NaN   
Column3           0.0         NaN         NaN  NaN   NaN   NaN     NaN   
Column4           0.0         NaN         NaN  NaN   NaN   NaN     NaN   

                   max  
num_reactions   4710.0  
num_comments   20990.0  
num_shares      3424.0  
num_likes       4710.0  
num_loves        657.0  
num_wows         278.0  
num_hahas        157.0  
num_sads          51.0  
num_angrys        31.0  
Column1            NaN  
Column2            NaN  
Column3            NaN  
Column4            NaN

In [5]:
data.isnull().sum()

status_id              0
status_type            0
status_published       0
num_reactions          0
num_comments           0
num_shares             0
num_likes              0
num_loves              0
num_wows               0
num_hahas              0
num_sads               0
num_angrys             0
Column1             7050
Column2             7050
Column3             7050
Column4             7050
dtype: int64

In [6]:
data['status_type'].value_counts()

status_type
photo     4288
video     2334
status     365
link        63
Name: count, dtype: int64

In [7]:
data['status_id'].unique()

array(['246675545449582_1649696485147474',
       '246675545449582_1649426988507757',
       '246675545449582_1648730588577397', ...,
       '1050855161656896_1060126464063099',
       '1050855161656896_1058663487542730',
       '1050855161656896_1050858841656528'], dtype=object)

In [8]:
len(data['status_id'].unique())

6997

In [9]:
len(data['status_published'].unique())

6913

In [10]:
data.drop(['Column1', 'Column2', 'Column3', 'Column4'], axis=1, inplace=True)
data

status_id status_type status_published  \
0      246675545449582_1649696485147474       video   4/22/2018 6:00   
1      246675545449582_1649426988507757       photo  4/21/2018 22:45   
2      246675545449582_1648730588577397       video   4/21/2018 6:17   
3      246675545449582_1648576705259452       photo   4/21/2018 2:29   
4      246675545449582_1645700502213739       photo   4/18/2018 3:22   
...                                 ...         ...              ...   
7045  1050855161656896_1061863470556065       photo   9/24/2016 2:58   
7046  1050855161656896_1061334757275603       photo  9/23/2016 11:19   
7047  1050855161656896_1060126464063099       photo  9/21/2016 23:03   
7048  1050855161656896_1058663487542730       photo   9/20/2016 0:43   
7049  1050855161656896_1050858841656528       photo  9/10/2016 10:30   

      num_reactions  num_comments  num_shares  num_likes  num_loves  num_wows  \
0               529           512         262        432         92         3   
1               150             0           0        150          0         0   
2               227           236          57        204         21         1   
3               111             0           0        111          0         0   
4               213             0           0        204          9         0   
...             ...           ...         ...        ...        ...       ...   
7045             89             0           0         89          0         0   
7046             16             0           0         14          1         0   
7047              2             0           0          1          1         0   
7048            351            12          22        349          2         0   
7049             17             0           0         17          0         0   

      num_hahas  num_sads  num_angrys  
0             1         1           0  
1             0         0           0  
2             1         0           0  
3             0         0           0  
4             0         0           0  
...         ...       ...         ...  
7045          0         0           0  
7046          1         0           0  
7047          0         0           0  
7048          0         0           0  
7049          0         0           0  

[7050 rows x 12 columns]

In [11]:
data.drop(['status_id', 'status_published'], axis=1, inplace=True)
data

status_type  num_reactions  num_comments  num_shares  num_likes  \
0          video            529           512         262        432   
1          photo            150             0           0        150   
2          video            227           236          57        204   
3          photo            111             0           0        111   
4          photo            213             0           0        204   
...          ...            ...           ...         ...        ...   
7045       photo             89             0           0         89   
7046       photo             16             0           0         14   
7047       photo              2             0           0          1   
7048       photo            351            12          22        349   
7049       photo             17             0           0         17   

      num_loves  num_wows  num_hahas  num_sads  num_angrys  
0            92         3          1         1           0  
1             0         0          0         0           0  
2            21         1          1         0           0  
3             0         0          0         0           0  
4             9         0          0         0           0  
...         ...       ...        ...       ...         ...  
7045          0         0          0         0           0  
7046          1         0          1         0           0  
7047          1         0          0         0           0  
7048          2         0          0         0           0  
7049          0         0          0         0           0  

[7050 rows x 10 columns]

In [12]:
data.dtypes

status_type      object
num_reactions     int64
num_comments      int64
num_shares        int64
num_likes         int64
num_loves         int64
num_wows          int64
num_hahas         int64
num_sads          int64
num_angrys        int64
dtype: object

In [13]:
le = LabelEncoder()
data['status_type'] = le.fit_transform(data['status_type'])
data

status_type  num_reactions  num_comments  num_shares  num_likes  \
0               3            529           512         262        432   
1               1            150             0           0        150   
2               3            227           236          57        204   
3               1            111             0           0        111   
4               1            213             0           0        204   
...           ...            ...           ...         ...        ...   
7045            1             89             0           0         89   
7046            1             16             0           0         14   
7047            1              2             0           0          1   
7048            1            351            12          22        349   
7049            1             17             0           0         17   

      num_loves  num_wows  num_hahas  num_sads  num_angrys  
0            92         3          1         1           0  
1             0         0          0         0           0  
2            21         1          1         0           0  
3             0         0          0         0           0  
4             9         0          0         0           0  
...         ...       ...        ...       ...         ...  
7045          0         0          0         0           0  
7046          1         0          1         0           0  
7047          1         0          0         0           0  
7048          2         0          0         0           0  
7049          0         0          0         0           0  

[7050 rows x 10 columns]

In [14]:
data['status_type'] = data['status_type'].astype(np.int64)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7050 entries, 0 to 7049
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   status_type    7050 non-null   int64
 1   num_reactions  7050 non-null   int64
 2   num_comments   7050 non-null   int64
 3   num_shares     7050 non-null   int64
 4   num_likes      7050 non-null   int64
 5   num_loves      7050 non-null   int64
 6   num_wows       7050 non-null   int64
 7   num_hahas      7050 non-null   int64
 8   num_sads       7050 non-null   int64
 9   num_angrys     7050 non-null   int64
dtypes: int64(10)
memory usage: 550.9 KB


In [15]:
X, y = data.drop('status_type', axis=1), data['status_type']

Singular Value Decomposition

In [33]:
model = lda(solver='svd')
model.fit(X, y)

In [18]:
model.coef_

array([[-2.70011711e-01, -1.42377355e-04, -3.90320555e-05,
         2.70999572e-01,  2.60728448e-01,  2.68991241e-01,
         2.69249565e-01,  2.24133191e-01,  2.15261991e-01],
       [ 1.62521886e-01, -1.11173779e-04, -1.01799181e-03,
        -1.62586716e-01, -1.69231167e-01, -1.49357037e-01,
        -1.56058583e-01, -1.53579640e-01, -1.33801890e-01],
       [-3.09967016e-01, -8.43135365e-05, -1.40927498e-03,
         3.11257256e-01,  3.00926492e-01,  3.23519785e-01,
         3.03402812e-01,  4.18889930e-01,  2.64664181e-01],
       [-2.42821400e-01,  2.21275655e-04,  2.09168521e-03,
         2.42712068e-01,  2.56811990e-01,  2.16543189e-01,
         2.31994197e-01,  2.10597379e-01,  1.98619782e-01]])

In [19]:
model.intercept_

array([-4.91862   , -0.42219696, -3.31980414, -1.59518135])

In [28]:
U, S, V = np.linalg.svd(X)

Least Squares

In [34]:
X, y = data.drop('status_type', axis=1), data['status_type']

In [35]:
model = lda(solver='lsqr')
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
grid = dict()
grid['shrinkage'] = np.arange(0, 1, 0.01)

In [36]:
search  = GridSearchCV(model, grid, scoring='accuracy', cv=cv, n_jobs=-1)
results = search.fit(X, y)

In [37]:
print(f'Mean accuracy: {results.best_score_}')

Mean accuracy: 0.7114893617021278


In [38]:
print(f'Config: {results.best_params_}')

Config: {'shrinkage': 0.0}


In [39]:
results.best_estimator_.coef_

array([[-1.57517724e-02, -3.28916770e-05,  7.05039425e-04,
         1.77203796e-02,  1.09710240e-02,  4.87473514e-03,
         1.50024604e-02,  1.20876717e-02, -3.38135190e-03],
       [ 4.17027379e-01, -1.67038641e-06, -2.74476085e-04,
        -4.16112061e-01, -4.19232684e-01, -4.13711044e-01,
        -4.10547140e-01, -3.65839592e-01, -3.52643402e-01],
       [-5.57297602e-02,  2.52051044e-05, -6.65981385e-04,
         5.80009182e-02,  5.11918889e-02,  5.94342359e-02,
         4.91750967e-02,  2.06954975e-01,  4.60488838e-02],
       [ 1.14539746e-02,  3.30967778e-04,  2.83696629e-03,
        -1.05831845e-02,  7.05234242e-03, -4.76030920e-02,
        -2.22740578e-02, -1.45582447e-03, -2.00330095e-02]])

In [40]:
results.best_estimator_.intercept_

array([-5.08115307, -0.58457336, -3.48242688, -1.75787836])